# This demo will demo how to make the job dependent on previous jobs
# Also it will demo about how to use output generated in previous job into current job
name: demo-on-using-previous-jobs output in current job
on: [workflow_dispatch, push]
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      JOB1_OUTPUT: ${{ steps.step1.outputs.step1_output }} 
    steps:
    - name: Generate Output step
      id: step1
      run: |
        echo "step1_output=Output1 from step1" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
     - name: Assign Output of job1 in env var ENV1 and print it
       env:
         ENV1: ${{ needs.job1.outputs.JOB1_OUTPUT }}
       run: |
         echo $ENV1
  job3:
    runs-on: ubuntu-latest
    needs: [job1,job2]
    steps:
    - name: print output generated in job1
      run: |
        echo "This is the output generated in Job1:- ${{ needs.job1.outputs.JOB1_OUTPUT }}
        
