# This Example will demo how to take the input from user at runtime and use it in our workflow for evaluation
name: Demo on User Input
on: 
  workflow_dispatch:
    inputs:
      name:
        description: Please Enter your Name
        required: true
      location:
        description: Please Enter Your Location
        required: true
      company:
        description: Please Enter Company you Worked in
        required: true
      gender:
        description: Please select the Gender
        type: choice
        options:
          - Male
          - Female
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: print the user inputs
      run: |
        echo "User Name      :- ${{ inputs.name }}"
        echo "User Location  :- ${{ inputs.location }}"
        echo "User Company   :- ${{ inputs.company }}"
        echo "User Gender is :- ${{ inputs.gender }}"
